### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by Ibrahim-develop4444** [musab-r/React-Native-Hijri-Calendar#2]
undefined is not an object (evaluating '_this.props.utils.initialmoment') ;

i had this problem and it is duo to this  line 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84371981/123333052-9091d900-d541-11eb-8253-7bf667cc29d7.png)

**Comment by musab-r** [comment]
> undefined is not an object (evaluating '_this.props.utils.initialmoment') ;
> 
> i had this problem and it is duo to this line ![MicrosoftTeams-image](https://user-images.githubusercontent.com/84371981/123333052-9091d900-d541-11eb-8253-7bf667cc29d7.png)

Hi,

The method is defined in utils\hijri_utils.js file directory.  You need to import the file, from where you are passing the context. Hope this will solve your problem.
