### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by mahammad72** [musab-r/React-Native-Hijri-Calendar#3]
Can you please provide your package.json file so we need to check plugin which you used in this app ?

**Comment by musab-r** [comment]
Hi,
Unfortunately, I can't share that now. It was one of the specifications and I used the moment-hijri.js as the external source to make it runnable for react-native framework. As there wasn't much support for hijri-calendar in react-native. Will check if there's any dependency, I'll share it.

**Comment by mahammad72** [comment]
Ok zajakallah
